geodjango_boilerplate/map/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.webmap, name='webmap'),
]

geodjango_boilerplate/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from .core import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^map/', include('geodjango_boilerplate.map.urls', namespace='map')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geodjango_boilerplate/core/models.py
from django.db import models

# Create your models here.

geodjango_boilerplate/map/models.py
from django.db import models

# Create your models here.

geodjango_boilerplate/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

geodjango_boilerplate/map/views.py
from django.shortcuts import render


def webmap(request):
    return render(request, 'map/webmap.html')

geodjango_boilerplate/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} GeoDjango Example {% endblock title %}</title>
    {% include 'includes/favicons.html' %}
    <!-- Bootstrap -->
    <link href="{% static 'libs/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    {% block extras_assets %}
    {% endblock extras_assets %}

</head>
<body>

{% include 'includes/navbar.html' %}

<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div><!--/.container-->

<script src="{% static 'libs/jquery-1.12.4/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>

{% block extras_js %}
{% endblock extras_js %}

</body>
</html>

geodjango_boilerplate/core/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <h1>GeoDjango Boilerplate</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ab at consectetur corporis cupiditate
            distinctio, ea eius eum eveniet expedita impedit laborum necessitatibus, nobis omnis quibusdam saepe
            tenetur unde voluptates.
        </p>

        <p>
            <a class="btn btn-lg btn-primary" href="{% url 'map:webmap' %}" role="button">View the project &raquo;</a>
        </p>
    </div>

{% endblock content %}

geodjango_boilerplate/core/templates/includes/favicons.html
{% load static %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="imageimg/favicon/png" sizes="192x192" href="{% static 'img/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'img/favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">

geodjango_boilerplate/core/templates/includes/navbar.html
{% load activeurl %}

<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">GeoDjango Boilerplate</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            {% activeurl %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'map:webmap' %}">WebMap</a></li>
                </ul>
            {% endactiveurl %}

            {% activeurl %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'admin:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Admin</a>
                    </li>
                </ul>
            {% endactiveurl %}

        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->

geodjango_boilerplate/map/templates/map/webmap.html
{% extends 'base.html' %}
{% load static %}

{% block extras_assets %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
{% endblock extras_assets %}


{% block title %} Leaflet Map {% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div id="map"></div>
        </div><!-- .col-md-12 -->
    </div><!-- .row -->
{% endblock content %}

{% block extras_js %}

    <script src="{% static 'libs/leaflet/leaflet.js' %}"></script>

    <script>

        var mbAttr = 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            mbUrl = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw';

        var grayscale = L.tileLayer(mbUrl, {id: 'mapbox.light', attribution: mbAttr}),
            streets = L.tileLayer(mbUrl, {id: 'mapbox.streets', attribution: mbAttr});

        var map = L.map('map', {
            center: [-7.177200, -36.795959],
            zoom: 8,
            layers: [streets]
        });

        var baseLayers = {
            "Grayscale": grayscale,
            "Streets": streets
        };

        var overlays = {};

        L.control.layers(baseLayers, overlays).addTo(map);

    </script>

{% endblock extras_js %}